### ISSUE TITLE
forks diverging

### ISSUE THREAD

**Issue by kenyon** [SecurityCentral/classification-banner-fork#3]
I see some commits going to https://github.com/fcaviggia/classification-banner but not here. Seems to me that the SecurityCentral version should be authoritative since it is the one packaged for EPEL. The divergence of these two repositories seems like a situation we ought to avoid.

**Comment by shawndwells** [comment]
Hey @kenyon, @redhatrises (who maintains this) will be out of office for a few days. Wanted to set expectations of a delayed response.

**Comment by redhatrises** [comment]
@kenyon Sorry for the late reply. 

@kenyon you have a great point. One of the discussions we were having internally is if a python script is the right strategy one moving forward. The reasoning is that a user can kill the banner with a `kill` command, windows appear behind the banner, and the banner is not enabled in the login screen. So, I have been looking into creating Gnome extensions to enable and show the banner in the login screen and as part of the menus which makes me wonder if the repo should be made authoritative. Thoughts?

**Comment by kenyon** [comment]
I'm not too concerned about the implementation details for my current usage, but your GNOME extension idea sounds like an improvement. I just filed this issue out of concern that improvements to this existing implementation are diverging due to the two repositories. Also, I appreciate the fact that there is a classification banner in an official-ish repository like EPEL.

**Comment by kenyon** [comment]
Any update on this?

**Comment by redhatrises** [comment]
Well, we can divorce the forks and re-create the repo.... it will lose any historical-ness to it to some degree.

There is this BZ that was filed for this: https://bugzilla.redhat.com/show_bug.cgi?id=1751336
And (while the BZ may be closed), there is an internal plan in JIRA for this.

BTW, opening a case can help to raise priority.

**Comment by kenyon** [comment]
We're having a problem with the banner on multiple monitors, and I think the situation might be improved due to some changes in fcaviggia/classification-banner. So I'm going to try to merge fcaviggia/classification-banner into SecurityCentral/classification-banner. If I'm successful, I'll leave another comment here with a link to the branch in my fork.

The problem is that the fcaviggia repository didn't become readonly and direct people to SecurityCentral, and he kept merging patches, even though he did basically state that SecurityCentral should be the canonical repository: https://github.com/fcaviggia/classification-banner/pull/43#issuecomment-586636872

**Comment by kenyon** [comment]
BTW I would suggest not to recreate the SecurityCentral repo based on the fcaviggia one, if that's what you're suggesting. That would lose a bunch of work that I did.

**Comment by kenyon** [comment]
The merge conflicts in banner.py are a massive disaster. @fcaviggia can you set your fork to read-only so that we don't continue making this problem worse? Thanks.

**Comment by fcaviggia** [comment]
Sure, I just don't have the time to maintain this anymore...

**Comment by fcaviggia** [comment]
It's done - thanks for continuing my work...

**Comment by kenyon** [comment]
This is where I'm making my attempt to merge the changes from the fcaviggia repo to the SecurityCentral one: https://github.com/kenyon/classification-banner/tree/big-merge
